# Generated by Django 5.0.6 on 2024-06-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeradmin',
            options={'verbose_name': 'EmployerAdmin'},
        ),
    ]
