# Generated by Django 5.0.6 on 2024-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employeradmin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeradmin',
            options={'verbose_name': 'EmployerAdmin', 'verbose_name_plural': 'Employer Admins'},
        ),
    ]
