# Generated by Django 5.0.6 on 2024-06-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_careertimestamp_worker_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employer'),
        ),
    ]
