# Generated by Django 5.0.6 on 2024-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employer_email_alter_employer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeradmin',
            options={'verbose_name': 'Employer Admin', 'verbose_name_plural': 'Employer Admins'},
        ),
        migrations.RemoveField(
            model_name='employeradmin',
            name='name',
        ),
        migrations.AlterField(
            model_name='employeradmin',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
