# Generated by Django 5.0.6 on 2024-06-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employeradmin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeradmin',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
