# Generated by Django 5.0.6 on 2024-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employeradmin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='duties',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
